
version: '3.8'
services:
  web:
    build:
      context: ./
      target: runner
    env_file:
      - .env.docker
    volumes:
      - .:/app
    command: npm run dev
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development